# Site settings
title: Matheus Portela
email: matheus.v.portela@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Brazilian software developer trying to create a better world.
baseurl: / # the subpath of your site, e.g. /blog
url: http://www.matheusportela.com # the base hostname & protocol for your site
github_username:  matheusportela
author:
  name: Matheus Portela

# Build settings
markdown: kramdown

# Permalinks
permalink: :title

# Plugins
plugins:
  - jekyll-feed

# Atom RSS
feed:
  path: /atom.xml
