# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matheus Portela
email: matheus.v.portela@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Brazilian software developer trying to create a better world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matheusportela.github.io" # the base hostname & protocol for your site
twitter_username: matheusvportela
github_username:  matheusportela

# Build settings
markdown: kramdown
